### ISSUE TITLE
logo update

### ISSUE THREAD

**Issue by oeon** [SLUGIS/logo#2]
I noticed the logo has been modified https://twitter.com/slugis3400 ...recommend updating here and elsewhere. Cc @hpanno @tabiko

**Comment by hpanno** [comment]
Will do, thanks Joe.

Hannah Panno
hkpanno@gmail.com
951.265.9811

**Comment by tabiko** [comment]
Yeah, I did that...made a "social media" logo and added the SLO County Fire
Dept name so CAL FIRE doesn't get kooky about using "CAL FIRE SLU" on an
unofficial logo.

**Comment by hpanno** [comment]
github has been updated with current logo

Hannah Panno
hkpanno@gmail.com
951.265.9811
